# Build Settings

markdown: kramdown
theme: jekyll-theme-minimal

title: gRPC - Up and Running
description: This repository accompanies gRPC - Up and Running. All the samples are written in both Go language and Java language. Feel free to check out the repository and try out.