# Build Settings

markdown: kramdown
theme: jekyll-theme-minimal

title: gRPC - Up and Running
description: Welcome to the resource repository of the book "gRPC - Up and Running.

github:
  is_project_page: true
  repository_url: https://github.com/grpc-up-and-running/samples
  repository_nwo: grpc-up-and-running/samples
  is_user_page: false